### ISSUE TITLE
The source is missing

### ISSUE THREAD

**Issue by vamenard** [olios123/HardcoreMode#1]
There is no source code in the git repo.

**Comment by olios123** [comment]
All the files that should be in the repository are here.

**Comment by olios123** [comment]
All the files that should be in the repository are here.

**Comment by vamenard** [comment]
Well it only shows the yml files. You have a typo in the readme, it says "HardocreMode". I uninstalled the plugin, it was causing issues on the authentification, 1 time out of 2 I was unable to login (I'm using Spigot 1.20.1).

**Comment by olios123** [comment]
This is possible because it has not been tested or prepared for version 1.20
